### ISSUE TITLE
512

### ISSUE THREAD

**Issue by Inferencer** [OpenTalker/SadTalker#347]
I am running locally since the latest update but I dont see where the inference.py has incuded 512, I am using 
`python inference.py --driven_audio examples/driven_audio/bus_chinese.wav --source_image C:/Users/leolo/Documents/original/output_0067.png --result_dir results --still --size 512 --preprocess extfull --cpu`

and i'm not getting any errors and it's all working fine I just want to make sure the 512 is being used and it's not reverting to default 256

**Comment by luochaolun** [comment]
请问你是怎么让它在cpu下运行的，我在cpu下运行出错

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by vinthony** [comment]
> I am running locally since the latest update but I dont see where the inference.py has incuded 512, I am using `python inference.py --driven_audio examples/driven_audio/bus_chinese.wav --source_image C:/Users/leolo/Documents/original/output_0067.png --result_dir results --still --size 512 --preprocess extfull --cpu`
> 
> and i'm not getting any errors and it's all working fine I just want to make sure the 512 is being used and it's not reverting to default 256

hi, in `full`,  we will crop the images and run the code in the crop region, after that, we paste back to the small size of the video. The results might be similar in both situations since the cropped face might be in a resolution of around 256. 

You can try to use the `crop` options to have a try.

eg, 512:

https://github.com/OpenTalker/SadTalker/assets/4397546/163903bc-8478-489a-a634-ac9040d7949d


256:

https://github.com/OpenTalker/SadTalker/assets/4397546/ccfad7c4-72d4-424a-98b0-59df94fb6964

**Comment by Inferencer** [comment]
> 请问你是怎么让它在cpu下运行的，我在cpu下运行出错
> 
> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

I had the same problem with another repo but I can't remember how I fixed it in the end as I know chatgpt said I had to edit a file in that spesific repo so i'm not sure how it's working with this without the error, but you try try the following, save the inference.py file as a backup as we are going to edit the file and I want to make sure if it breaks you have a backup

in the inference.py file edit the following 

`preprocess_model = CropAndExtract(sadtalker_paths, device)`

to

`preprocess_model = CropAndExtract(sadtalker_paths, torch.device('cpu'))`

then change the lines

```
audio_to_coeff = Audio2Coeff(sadtalker_paths, device)
animate_from_coeff = AnimateFromCoeff(sadtalker_paths, device)

to
```

audio_to_coeff = Audio2Coeff(sadtalker_paths, torch.device('cpu'))
animate_from_coeff = AnimateFromCoeff(sadtalker_paths, torch.device('cpu'))

After making these changes, the code should run on the CPU even if CUDA is not available, and you should no longer encounter the CUDA-related error.
```

```

**Comment by luochaolun** [comment]
> torch.device('cpu')

非常感谢，不过
按这个试了，改过后还是上边的错误
